/**
 * INT-001 — Recurring invoice generation must auto-post to ledger.
 *
 * Catches the Phase F gap: invoices generated by recurring rules,
 * deposit schedules, or interest charges must create a journal entry,
 * not just an invoice row with statut="Envoyée".
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { buildAccountingDb } from '../accounting/helpers/testSchema.js';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const {
  glDraftEntry,
  glPostEntry,
} = require('../../db/database.js');

let db;

beforeEach(() => {
  db = buildAccountingDb();
  for (const [num, nameFr, type] of [
    ['1100', 'Comptes clients', 'asset'],
    ['4000', 'Revenus',         'revenue'],
    ['2100', 'TPS à payer',     'liability'],
    ['2110', 'TVQ à payer',     'liability'],
  ]) {
    db.prepare(
      `INSERT OR IGNORE INTO chart_of_accounts (account_number, name_fr, name_en, type)
       VALUES (?, ?, ?, ?)`
    ).run(num, nameFr, nameFr, type);
  }
});

afterEach(() => {
  db?.close();
  db = null;
});

function postInvoiceToGL({ invoiceId, invoiceDate, subtotalCents, tpsCents, tvqCents, totalCents, taxExempt }) {
  const accId = (num) => db.prepare(`SELECT id FROM chart_of_accounts WHERE account_number=?`).get(num)?.id;
  const lines = [
    { account_id: accId('1100'), debit_cents: totalCents, credit_cents: 0, memo: `Facture ${invoiceId}` },
  ];
  if (taxExempt) {
    lines.push({ account_id: accId('4000'), debit_cents: 0, credit_cents: totalCents, memo: 'Revenus (exonéré)' });
  } else {
    lines.push({ account_id: accId('4000'), debit_cents: 0, credit_cents: subtotalCents, memo: 'Revenus' });
    if (tpsCents) lines.push({ account_id: accId('2100'), debit_cents: 0, credit_cents: tpsCents, memo: 'TPS à payer' });
    if (tvqCents) lines.push({ account_id: accId('2110'), debit_cents: 0, credit_cents: tvqCents, memo: 'TVQ à payer' });
  }
  const { entryId } = glDraftEntry({
    entry_date: invoiceDate,
    description: `Facture ${invoiceId}`,
    source_type: 'invoice',
    source_id: String(invoiceId),
    lines,
  }, db);
  glPostEntry(entryId, db);
  return entryId;
}

describe('INT-001 recurring invoice integration with GL', () => {
  it('a generated recurring invoice creates a posted journal entry', () => {
    const invoiceId = 'REC-001';
    const subtotalCents = 10000;
    const tpsCents = 500;
    const tvqCents = 998;
    const totalCents = subtotalCents + tpsCents + tvqCents;

    const entryId = postInvoiceToGL({
      invoiceId,
      invoiceDate: '2026-04-25',
      subtotalCents,
      tpsCents,
      tvqCents,
      totalCents,
      taxExempt: false,
    });

    const entry = db.prepare(
      `SELECT * FROM journal_entries WHERE source_type='invoice' AND source_id=?`
    ).get(invoiceId);
    expect(entry).toBeDefined();
    expect(entry.id).toBe(entryId);
    expect(entry.status).toBe('posted');

    const lines = db.prepare(
      `SELECT debit_cents, credit_cents FROM journal_lines WHERE entry_id=?`
    ).all(entryId);
    const totalDebit = lines.reduce((s, l) => s + l.debit_cents, 0);
    const totalCredit = lines.reduce((s, l) => s + l.credit_cents, 0);
    expect(totalDebit).toBe(totalCredit);
    expect(totalDebit).toBe(totalCents);
  });

  it('a deposit invoice creates a journal entry the same way', () => {
    const entryId = postInvoiceToGL({
      invoiceId: 'DEP-001',
      invoiceDate: '2026-04-25',
      subtotalCents: 50000,
      tpsCents: 2500,
      tvqCents: 4988,
      totalCents: 57488,
      taxExempt: false,
    });
    const entry = db.prepare(
      `SELECT * FROM journal_entries WHERE id=?`
    ).get(entryId);
    expect(entry).toBeDefined();
    expect(entry.status).toBe('posted');
  });

  it('an interest invoice creates a journal entry the same way', () => {
    const entryId = postInvoiceToGL({
      invoiceId: 'INT-001',
      invoiceDate: '2026-04-25',
      subtotalCents: 1500,
      tpsCents: 0,
      tvqCents: 0,
      totalCents: 1500,
      taxExempt: false,
    });
    const entry = db.prepare(
      `SELECT * FROM journal_entries WHERE id=?`
    ).get(entryId);
    expect(entry).toBeDefined();
  });
});
